### ISSUE TITLE
各种接口总报这个错误

### ISSUE THREAD

**Issue by wangxufire** [ali-sdk/ali-oss#108]
```
[2016-05-05 17:08:35.164] [ERROR] oss-logger - TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1429:5)
    at Client.proto.createRequest (/Users/madoka/Workspace/github/nodeoss/app/node_modules/ali-oss/lib/client.js:239:65)
    at Client.proto.request (/Users/madoka/Workspace/github/nodeoss/app/node_modules/ali-oss/lib/client.js:296:24)
    at next (native)
    at onFulfilled (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:65:19)
    at /Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:54:5
    at co (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:50:10)
    at toPromise (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:118:63)
    at next (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:99:29)
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1429:5)
    at Client.proto.createRequest (/Users/madoka/Workspace/github/nodeoss/app/node_modules/ali-oss/lib/client.js:239:65)
    at Client.proto.request (/Users/madoka/Workspace/github/nodeoss/app/node_modules/ali-oss/lib/client.js:296:24)
    at next (native)
    at onFulfilled (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:65:19)
    at /Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:54:5
    at co (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:50:10)
    at toPromise (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:118:63)
    at next (/Users/madoka/Workspace/github/nodeoss/app/node_modules/co/index.js:99:29)
```

给个思路这么调试

**Comment by wangxufire** [comment]
参数都是写死的字符串，这么久Received undefined呢

**Comment by rockuw** [comment]
`at Client.proto.createRequest (/Users/madoka/Workspace/github/nodeoss/app/node_modules/ali-oss/lib/client.js:239:65)`这行：

```js
headers['Content-Type'] = mime.lookup(params.mime || path.extname(params.object));
```

把params.object打印出来就好了。

**Comment by wangxufire** [comment]
params.object 是undefined

**Comment by dead-horse** [comment]
node@6 `path.extname` 不能传 undefined 了

**Comment by wangxufire** [comment]
确实是node6.0

**Comment by dead-horse** [comment]
贴一下你调接口时的参数

**Comment by wangxufire** [comment]
```
  result = yield ossClient.putBucketACL('nodeoss', 'oss-cn-qingdao', 'public-read');
  console.log(result);
```

**Comment by wangxufire** [comment]
能兼容下6.0 发个版本么

**Comment by wangxufire** [comment]
在问一下 有没有java sdk那样失败重试几次的配置？

**Comment by rockuw** [comment]
目前js sdk没有重试机制

**Comment by dead-horse** [comment]
试试 4.4.2

**Comment by wangxufire** [comment]
可以了
