### ISSUE TITLE
putMeta error,The specified bucket does not exist.

### ISSUE THREAD

**Issue by daledelv** [ali-sdk/ali-oss#1155]
pkg version: 6.17.0

Exception occurred when calling by document instance! 
[https://help.aliyun.com/document_detail/111412.html](https://help.aliyun.com/document_detail/111412.html)

And its type file is wrong.
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/13879432/189047300-edb7930b-30e8-46fc-a56d-ea3a857f244c.png">

My instance configuration is normal, and other methods can be called,such as put.

/Users/dally/Desktop/script/node_modules/ali-oss/lib/client.js:372
    err = new Error(msg);
          ^
Error [NoSuchBucketError]: The specified bucket does not exist.
    at Client.requestError (/Users/dally/Desktop/script/node_modules/ali-oss/lib/client.js:372:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.request (/Users/dally/Desktop/script/node_modules/ali-oss/lib/client.js:213:11)
    at async Client.proto.request (/Users/dally/Desktop/script/node_modules/ali-oss/lib/client.js:194:12)
    at async Client.copy (/Users/dally/Desktop/script/node_modules/ali-oss/lib/common/object/copyObject.js:41:18)
    at async Client.putMeta (/Users/dally/Desktop/script/node_modules/ali-oss/lib/object.js:191:10) {

**Comment by taotao7** [comment]
please check if the bucket exists first
