### ISSUE TITLE
Error message：callback twice!!!

### ISSUE THREAD

**Issue by csorz** [ali-sdk/ali-oss#1313]
- **Browser Version or Node Version**: Node 18.19.0
- **ali-oss Version**: 6.20.0
- **Mini Showcase Repository**: 
- **Network Resoponse Header x-oss-request-id**:

pages-multi-game-multi-game.pHFS6Hk3.js 这个脚本文件始终无法上传，出现报错callback twice!!!，100%复现。

[pages-multi-game-multi-game.pHFS6Hk3.zip](https://github.com/user-attachments/files/15963931/pages-multi-game-multi-game.pHFS6Hk3.zip)

当我把脚本文件内容清空时，可以上传成功。

### 参数：
{
  source: 'unpackage/dist/build/web',
  target: 'oss://x:x@x.oss-cn-hangzhou.aliyuncs.com/x/app/multi-game/',
  headers: { 'Cache-Control': 'no-cache' },
  timeout: 600000
}

### 错误信息：

[urllib:warn] [Tue Jun 25 2024 10:35:59 GMT+0800 (中国标准时间)] [2] [worker:19364] PUT http://域名/x/app/multi-game/assets/pages-multi-game-multi-game.pHFS6Hk3.js **callback twice!!!**
[urllib:warn] [Tue Jun 25 2024 10:35:59 GMT+0800 (中国标准时间)] [2] [worker:19364] ResponseError: write ECONNRESET, PUT http://域名/x/app/multi-game/assets/pages-multi-game-multi-game.pHFS6Hk3.js -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"域名:80:":1},"requests":{}}, socketHandledRequests: 2, socketHandledResponses: 1)
headers: {}
stack: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\@ytfee\npm-yt-deploy\node_modules\ali-oss\lib\client.js:487
      err = new Error(result.message);
            ^

Error [ResponseError]: write ECONNRESET, PUT http://域名/x/app/multi-game/assets/pages-multi-game-multi-game.pHFS6Hk3.js -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"域名:80:":1},"requests":{}}, socketHandledRequests: 2, socketHandledResponses: 1)
headers: {}
    at Client.requestError (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\@ytfee\npm-yt-deploy\node_modules\ali-oss\lib\client.js:487:13)
    at requestError.next (<anonymous>)
    at onFulfilled (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:65:19)
    at D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Client.co (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:50:10)
    at Client.toPromise (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:118:63)
    at next (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:99:29)
    at onRejected (D:\Git_yt\ipub-uniapp\yt-digital-resources\node_modules\co\index.js:85:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: -1,
  code: 'ResponseError'
}

**Comment by nerocho** [comment]
@csorz 请问你解决了吗？如何解决的。

**Comment by csorz** [comment]
现在还是偶发，出问题后只能略微修改文件内容打包时重新计算哈希。
带新哈希后缀的文件就不会出错...
例如： file.**pHFS6Hk3**.js

**Comment by nerocho** [comment]
这个我最后是这么解决的，给代码加个重试就好了。目前设置的是做多重试 3 次，目前再没遇到问题。基本上重试一两次就可以解决问题
