### ISSUE TITLE
NativeScript environment cann't use the ali-oss modules

### ISSUE THREAD

**Issue by giscafer** [ali-sdk/ali-oss#209]
there is the code sample in `main-page.js`:

> var OSS = require('ali-oss');

> var client = new OSS({
>     region: 'oss-cn-sxxxxxnzhen',
>     accessKeyId: 'LbbbqTbbbb9iWmw',
>     accessKeySecret: 'OFUxxxxgpVDQPYOV',
>     bucket: 'gz1ziton'
> });

`tns run android` occurs the Errors blow:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.uppicture/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "tty", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: Failed to find module: "tty", relative to: app/tns_modules/
	at
```

**Comment by luozhang002** [comment]
@giscafer nativescript考虑到使用量，应该短期内不会支持，用户可根据开源的openapi自己封装请求上传的。
