### ISSUE TITLE
执行例子的时候抛 Unexpected identifier 

### ISSUE THREAD

**Issue by GitNiko** [ali-sdk/ali-oss#22]
```js
var oss = require('ali-oss');

// Create a Bucket store instance.
var store = oss({
  accessKeyId: 'xxxxxx', //xxx这里保密
  accessKeySecret: 'xxxx',
  bucket: 'xxxx',
  region: 'oss-cn-hangzhou'
});
// List buckets in this account.
var result = yield store.listBuckets({
  "max-keys": 10
});

console.log(result);

```

按照给出的例子，结果抛出以下错误
```js
ewqwqe:node-oss lingjia$ node --harmony  index.js 
/Users/lingjia/workspace/node-oss/index.js:11
var result = yield store.listBuckets({
                   ^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

node版本v0.12.0  
实在没搞明白，特来请教:)

**Comment by dead-horse** [comment]
yield 必须在 generator function 里面才能使用。

```js
var oss = require('ali-oss');
var co = require('co');

// Create a Bucket store instance.
var store = oss({
  accessKeyId: 'xxxxxx', //xxx这里保密
  accessKeySecret: 'xxxx',
  bucket: 'xxxx',
  region: 'oss-cn-hangzhou'
});
// List buckets in this account.

co(function * () {
  var result = yield store.listBuckets({
    "max-keys": 10
  });
  console.log(result);
}).catch(function (err) {
  console.error(err.stack);
});

**Comment by GitNiko** [comment]
thanks😄
