### ISSUE TITLE
你好，请教一下我在ionic加入了ali-oss服务，为什么安卓6.0以上版本能用，以下版本不能用呢

### ISSUE THREAD

**Issue by cxpyear** [ali-sdk/ali-oss#237]
我在ionic加入了ali-oss服务，为什么安卓6.0以上版本能用，以下版本不能用呢

**Comment by liuxm6** [comment]
` error    TypeError: undefined is not a function
    at u (http://10.0.0.2:8100/lib/ali-oss/dist/aliyun-oss-sdk.min.js:4:10324)
    at Function.o.initOptions (http://10.0.0.2:8100/lib/ali-oss/dist/aliyun-oss-sdk.min.js:4:11319)
    at new o (http://10.0.0.2:8100/lib/ali-oss/dist/aliyun-oss-sdk.min.js:4:9848)
    at s.a (http://10.0.0.2:8100/lib/ali-oss/dist/aliyun-oss-sdk.min.js:5:14995)
    at new s (http://10.0.0.2:8100/lib/ali-oss/dist/aliyun-oss-sdk.min.js:5:15192)
    at new file (http://10.0.0.2:8100/app/util/file.js:9:22)
`

**Comment by liuxm6** [comment]
确实报这个错误

**Comment by mars-coder** [comment]
目前没有针对ionic或AngularJS做过兼容性适配，关于前端的兼容性版本今年我们有计划要做。
