### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by leizongmin** [ali-sdk/ali-oss#243]
上传文件时抛出以下异常：

```
TypeError: Cannot read property 'replace' of null
    at Client.proto._objectName (/my/app/node_modules/ali-oss/lib/object.js:496:14)
    at Client.proto._objectRequestParams (/my/app/node_modules/ali-oss/lib/object.js:479:15)
    at Client._initMultipartUpload (/my/app/node_modules/ali-oss/lib/multipart.js:203:21)
    at _initMultipartUpload.next (<anonymous>)
    at onFulfilled (/my/app/node_modules/co/index.js:65:19)
    at /my/app/node_modules/co/index.js:54:5
    at Promise._execute (/my/app/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/my/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/my/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.co (/my/app/node_modules/co/index.js:50:10)
    at Client.toPromise (/my/app/node_modules/co/index.js:118:63)
    at next (/my/app/node_modules/co/index.js:99:29)
    at onFulfilled (/my/app/node_modules/co/index.js:69:7)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/my/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/my/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/my/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/my/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/my/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/my/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/my/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/my/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by rockuw** [comment]
你传的object名是空的？

**Comment by leizongmin** [comment]
只是使用了`multipartUpload()`方法，并且确定`key`和`inputFile`都是不为空的，调用函数过了几分钟才报错

```typescript
    const ret = await store.multipartUpload(key, inputFile, {
        checkpoint,
        async progress(percentage: number, ckp: Record<string, any>) {
          debug(`上传进度:${Math.floor(percentage * 100)}%`);
          checkpoint = ckp;
        },
      });
```

**Comment by leizongmin** [comment]
不好意思，好像是因为传了空的文件名进去
