### ISSUE TITLE
put meta 未处理特殊字符

### ISSUE THREAD

**Issue by cncolder** [ali-sdk/ali-oss#266]
错误如下，但是想来想去似乎无解，因为即使这边做了 `encodeURI` 处理，OSS 控制台那边也不会 decode。不过控制台那边倒是可以手工修改成 `x-oss-meta-name: '屏幕快照 2012-12-22 上午12.12.12.png'`

话说阿里云是不是应该改进一下关于控制台问题的反馈渠道，现在的控制台有很多不尽如人意之处，可是提交工单的话工程师又不可能去管界面问题。

软硬件都还好，不能输在操作界面上。

```js
oss.put('test.jpg', Buffer.from('...', 'base64'), {
  mime: 'image/jpeg',
  meta: {
    name: '屏幕快照 2012-12-22 上午12.12.12.png'
  }
})
```

```bash
TypeError: The header content contains invalid characters, PUT https://example.oss-cn-beijing.aliyuncs.com/test.jpg -1 (connected: false, keepalive socket: false)
headers: {}
    at validateHeader (_http_outgoing.js:507:11)
    at ClientRequest.setHeader (_http_outgoing.js:511:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)
    at Object.request (https.js:233:15)
    at Object.requestWithCallback (/node_modules/ali-oss/node_modules/urllib/lib/urllib.js:745:19)
```

**Comment by binghaiwang** [comment]
x-oss-meta-xxx 这个是用户的数据， oss 这边是不能去做任何数据处理的，数据传进来是什么就会返回什么，因此在上传的时候自行进行encode, 在获取的时候自己去进行decode,  控制台也不会知道用户端的数据是如何进行encode的，所以也不会知道如何去decode进行解码。

**Comment by binghaiwang** [comment]
可以提交一个优化给控制台
