### ISSUE TITLE
如何判断文件是否存在？

### ISSUE THREAD

**Issue by buzai** [ali-sdk/ali-oss#436]
```
async function fileIsInOss(path) {
    console.log('fileIsInOss',path);
    //源OSS
    const client = new OSS({
        timeout: '3600s'
    })

    try {
        let flag = await client.head(path);
        return true;
    } catch (err) {
        throw new Error('路径不存在:' + path)
        return false;
    }
}
```

**Comment by buzai** [comment]
但是 返回报错了？
```
headers: {}
    at Client.requestError (/home/chenhao/code/server_ossvideo_new/node_modules/.4.13.2@ali-oss/lib/client.js:473:13)
    at requestError.next (<anonymous>)
    at onFulfilled (/home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:65:19)
    at /home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:54:5
    at new Promise (<anonymous>)
    at Client.co (/home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:50:10)
    at Client.toPromise (/home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:118:63)
    at next (/home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:99:29)
    at onRejected (/home/chenhao/code/server_ossvideo_new/node_modules/.4.6.0@co/index.js:85:7)
    at <anonymous> name: 'RequestError', status: -1, code: 'RequestError' }

```

**Comment by buzai** [comment]
这个所谓的 head 函数 接受的是 什么到底， 是 oss 上的文件名么？

**Comment by buzai** [comment]
还是 oss 上的路径

**Comment by buzai** [comment]
{ RequestError: socket hang up (req "error"),
显示 超时 到底是要 超时 还是说 文件是不存在的

**Comment by binghaiwang** [comment]
object name 不是你本地文件路径， 你是node用户吧？

**Comment by buzai** [comment]
@binghaiwang 对的我是 nodejs 的， 我现在 试试发先 name 可以是 oss 上的路径。这样判断出文件是否在上面，但是 有个问题， 他是通过 捕捉错误来获得不存在的，导致我的 主程序 捕捉了这个错误，捉急啊

**Comment by binghaiwang** [comment]
我们这边对外提供的都是generator函数， 这个直接接在async await 是不行的，你得想办法用co+promise或oss.wrapper+promise包装一层

**Comment by buzai** [comment]
@binghaiwang  谢谢你了啊 我想想
