### ISSUE TITLE
gzip 报错

### ISSUE THREAD

**Issue by 8427003** [ali-sdk/ali-oss#555]
put 时，options 加gzip响应头css和js文件报错。
我测试了，跟bom头无关。有无bom头都报错。

```
========error: h5-share/static/js/test.js { Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 1
raw xml: 123123123123aa

    at error (/Users/lijun/git/h5-share/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/lijun/git/h5-share/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/lijun/git/h5-share/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/lijun/git/h5-share/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/lijun/git/h5-share/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/lijun/git/h5-share/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/Users/lijun/git/h5-share/node_modules/xml2js/lib/parser.js:354:19)
    at Client.parseXML (/Users/lijun/git/h5-share/node_modules/ali-oss/lib/client.js:444:9)
    at /Users/lijun/git/h5-share/node_modules/co/index.js:136:8
    at new Promise (<anonymous>) status: 200, requestId: '5BFB6AA601F3FC7EE7F5764E' }
```

**Comment by 8427003** [comment]
请关闭这个issue，需要自行gzip文件。是我自己没搞清使用方法。
