### ISSUE TITLE
windows + electron 4.0.1 + node 11.6 连续put() 几个文件后就报 Socket timeout

### ISSUE THREAD

**Issue by xraywu** [ali-sdk/ali-oss#588]
* **Browser Version or Node Version**: node 11.6 for windows, electron 4.0.1 环境
* **ali-oss Version**: 6.0.2
* **urllib Version**: 2.33.0
* **agentkeepalive Version**: 4.0.0

使用下列代码连续上传多个文件时，一段时间（约不到 1min）后，每个请求都会触发 urllib warning 表示 socket timeout：

```
async uploadFiles() {
	let OSS = require('ali-oss');
	let AgentKeepalive = require('agentkeepalive');
	let HttpClient = require('urllib').HttpClient;

	let agent = new AgentKeepalive({
		keepAlive: false
	});
	let urllib = new HttpClient({ agent: agent });
	let client = new OSS({
		region: ossRegion,
		accessKeyId: ossKey,
		accessKeySecret: ossSecret,
		bucket: ossBucket,
		urllib: urllib
	});
	for (let i in fileList) {
		let uploadStatus = await client.put(path_oss, path_local);
	}
}

await uploadFiles();
```

循环执行约5-6 次put后（大约30s-1min左右），之后每次 put 时都会触发如下 warning：

```
C:\Users\wegene\Desktop\work\appt\build\app-win32-x64\resources\app.asar\node_modules\urllib\lib\urllib.js:429 [urllib:warn] [Tue Jan 22 2019 23:34:50 GMT+0800 (中国标准时间)] [3] [worker:11072] ResponseError: Socket timeout
stack: Error: Socket timeout
    at Socket.onTimeout (C:\Users\wegene\Desktop\work\app\build\app-win32-x64\resources\app.asar\node_modules\agentkeepalive\lib\agent.js:304:23)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
done @ C:\Users\wegene\Desktop\work\app\build\app-win32-x64\resources\app.asar\node_modules\urllib\lib\urllib.js:429
handleRequestError @ C:\Users\wegene\Desktop\work\app\build\app-win32-x64\resources\app.asar\node_modules\urllib\lib\urllib.js:1027
emit @ events.js:187
socketErrorListener @ _http_client.js:391
emit @ events.js:187
emitErrorNT @ internal/streams/destroy.js:82
_tickCallback @ internal/process/next_tick.js:63
renderer.js:1 {name: "filename", url: "fileurl", res: {…}}
```

**Comment by xraywu** [comment]
@luozhang002 不传urllib用默认配置也会出这个问题，或者如果不传 urllib，直接传一个 agent 也是一样的。现在基本可以确定是 AgentKeepAlive 的问题，如果传一个不用 agent 的 urllib 就不会出现这个问题：

```
let urllib = new HttpClient({ agent: false });
let client = new OSS({
	region: ossRegion,
	accessKeyId: ossKey,
	accessKeySecret: ossSecret,
	bucket: ossBucket,
	urllib: urllib
});
```

**Comment by PeterRao** [comment]
文件过大，服务端超时释放链接了。大文件用分片上传接口。
