### ISSUE TITLE
上传大于100M的文件发生错误

### ISSUE THREAD

**Issue by czewail** [ali-sdk/ali-oss#627]
* **Browser Version**: Chrom 74
* **ali-oss Version**: 6.1.1
* **Network Resoponse Header x-oss-request-id**: 5CDE3093EBEC943E4C1F6427

```js
RequestError: Failed to fetch (req "error"), POST http://hmpimg.oss-cn-hangzhou.aliyuncs.com/upload/1558065299449-bb_h5.zip?uploads= -1 (connected: false, keepalive socket: false)
headers: {}
    at Client.requestError$ (http://dev.xxx.com/example.min.js:13152:19)
    at tryCatch (http://dev.xxx.com/example.min.js:27726:40)
    at Generator.invoke [as _invoke] (http://dev.xxx.com/example.min.js:27960:22)
    at Generator.prototype.<computed> [as next] (http://dev.xxx.com/example.min.js:27778:21)
    at tryCatch (http://dev.xxx.com/example.min.js:27726:40)
    at invoke (http://dev.xxx.com/example.min.js:27816:20)
    at http://dev.xxx.com/example.min.js:27859:11
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (http://dev.xxx.com/example.min.js:27858:16)
    at AsyncIterator.enqueue [as _invoke] (http://dev.xxx.com/example.min.js:27881:13)

Failed to fetch (req "error"), POST http://hmpimg.oss-cn-hangzhou.aliyuncs.com/upload/1558065299449-bb_h5.zip?uploads= -1 (connected: false, keepalive socket: false)
headers: {}
```
```js
class Upload {
  doUpload(file) {
        const client = new OSS({
            accessKeyId: 'xxx',
            accessKeySecret: 'xxx',
            endpoint: 'oss-cn-hangzhou.aliyuncs.com',
            region: 'oss-cn-hangzhou',
            bucket: 'hmpimg',
        });
        return this.multipartUpload(client, `upload/${Date.now()}-${file.name}`, file);
    }
    multipartUpload(client, objectKey, localFile) {
        return client.multipartUpload(objectKey, localFile, {
            partSize: 1000 * 1024,
        })
            .then((res) => res.url);
    }
}
```

**Comment by Ari1c** [comment]
您好，multipartUpload我尝试一下上传>100M文件是没有问题的，您可以看下api的使用，有log的话最好

**Comment by czewail** [comment]
@Ari1c 排查出来是http下无法上传 换成https就可以上传100M以上的了
