### ISSUE TITLE
特殊命名文件名签名冲突

### ISSUE THREAD

**Issue by yyman001** [ali-sdk/ali-oss#681]
* **Browser Version or Node Version**:
* **ali-oss Version**: 5.0.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

```js
let url_a = 'http://xf-drama-material-dev.oss-cn-hangzhou.aliyuncs.com/demo/map_pack20191030656164.json'
let url_b = 'http://xf-drama-material-dev.oss-cn-hangzhou.aliyuncs.com/material/node/dev/project_data/26/character-horizontal_CHM335873624978227200_y9j%7Bq4ws%24wu%7D%21%24lc5kpw796ba62azs%210.json'

当前状态: 开启原图保护, 图片开启自定义水印样式
使用 url_a 路径签名`正常`, 使用 url_b `签名错误`(url_b 在未开启原图保护,可以直接访问)
 错误信息如下:
```
浏览器页面访问:
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>5DBC00A7CBDEAA323213F5CE</RequestId>
<HostId>xf-drama-material-dev.oss-cn-hangzhou.aliyuncs.com</HostId>
<Key>
material/node/dev/project_data/26/character-horizontal_CHM335873624978227200_y9j%7Bq4ws%24wu%7D%21%24lc5kpw796ba62azs%210.json
</Key>
</Error>
```
使用接口请求会提示404/403, 但文件在管理台是可以看到的
```js

      { Error: cannot GET /material/node/dev/project_data/26/character-horizontal_CHM335873624978227200_y9j%257Bq4ws%2524wu%257D%2521%2524lc5kpw796ba62azs%25210.json?OSSAccessKeyId=LTAIGliWihVUjTKj&Expires=1572605992&Signature=mFeJbdy3tfcDyuHnz1ANcI19xQk%3D (403)
    at Response.toError (E:\git\material-node-images-merge\node_modules\superagent\lib\node\response.js:94:15)
    at ResponseBase._setStatusProperties (E:\git\material-node-images-merge\node_modules\superagent\lib\response-base.js:123:16)
    at new Response (E:\git\material-node-images-merge\node_modules\superagent\lib\node\response.js:41:8)
    at Request._emitResponse (E:\git\material-node-images-merge\node_modules\superagent\lib\node\index.js:742:20)
    at ClientRequest.req.once.res (E:\git\material-node-images-merge\node_modules\superagent\lib\node\index.js:920:32)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
        status: 403,
        text: undefined,
        method: 'GET',
        path: '/material/node/dev/project_data/26/character-horizontal_CHM335873624978227200_y9j%257Bq4ws%2524wu%257D%2521%2524lc5kpw796ba62azs%25210.json?OSSAccessKeyId=LTAIGliWihVUjTKj&Expires=1572605992&Signature=mFeJbdy3tfcDyuHnz1ANcI19xQk%3D' }

```
应该是我这个复杂的随机文件名跟签名冲突了? 不开启原图包含,不签名可以访问
现在是否能在不修正原来的数据下签名和访问`url_b` ?
签名语法是使用默认的,如果是get方式访问有问题, 是否可以使用 post 方式访问签名后的文件? 是否可以提供demo? 感谢~

**Comment by PeterRao** [comment]
![image](https://user-images.githubusercontent.com/1611647/68095972-a6740580-fee8-11e9-8907-2b2847e7e26e.png)
是不是传被url encodeo过的 url 了。
decode 下 url 传进去
