### ISSUE TITLE
下载文件时提示ResponseError: unable to verify the first certificate

### ISSUE THREAD

**Issue by jiapeng007** [ali-sdk/ali-oss#690]
* **Browser Version or Node Version**:10.15.3
* **ali-oss Version**: 6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

我在使用ali-oss下载文件的时候报下面的错误。现在的问题是，不是所有机器上都会有下面这个错误。还请各位帮忙分析一下原因。
[2019-11-21T09:41:16.482] [ERROR] err-logger - { ResponseError: unable to verify the first certificate, GET https://wabutler.oss-cn-beijing.aliyuncs.com/?prefix=product%2Fpos%2F&delimiter=%2F -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"wabutler.oss-cn-beijing.aliyuncs.com:443::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Client.requestError (C:\wabutler\cashier\wabutler-pos\resources\app.asar\node_modules\ali-oss\lib\client.js:466:13)
    at Client.request (C:\wabutler\cashier\wabutler-pos\resources\app.asar\node_modules\ali-oss\lib\client.js:317:22)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'ResponseError', status: -1, code: 'ResponseError' }
[2019-11-21T09:58:01.796] [ERROR] err-logger - { ResponseError: unable to verify the first certificate, GET https://wabutler.oss-cn-beijing.aliyuncs.com/?prefix=product%2Fpos%2F&delimiter=%2F -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"wabutler.oss-cn-beijing.aliyuncs.com:443::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)

**Comment by PeterRao** [comment]
![image](https://user-images.githubusercontent.com/1611647/69837597-9999c600-128a-11ea-9e66-8b95d45deffa.png)
这个url打开会报这种错，可能是其他原因，建议弄个纯文本试一下。
