### ISSUE TITLE
RequestError: getaddrinfo ENOTFOUND status -1

### ISSUE THREAD

**Issue by tokenl** [ali-sdk/ali-oss#733]
在使用ali-oss上传文件的时候，报下面这个错
```
{ RequestError: getaddrinfo ENOTFOUND ************** .svg -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1008,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets" 

headers: {}
    at Client.requestError (/Users/eden/Documents/dev/frontend2/node_modules/ali-oss/lib/client.js:410:13)
    at Client.request (/Users/eden/Documents/dev/frontend2/node_modules/ali-oss/lib/client.js:263:22)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'RequestError', status: -1, code: 'RequestError' }

```

看了下源码，注释有说明 status -1 是指网络问题，但还是不太明白具体为啥，偶尔会成功上传，但是大多数时候不行。

**Comment by PeterRao** [comment]
并发数过大
