### ISSUE TITLE
上传文件报错RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by jackieli123723** [ali-sdk/ali-oss#777]
## 环境 

```
$ node -v
v10.12.0

  "ali-oss": "^6.4.0",
```

报错信息如下 

```

(node:16176) UnhandledPromiseRejectionWarning: RangeError [ERR_OUT_OF_RANGE]: The value of "end" is out of range. It must be >= 0 and <= 2 ** 53 - 1. Received -1
    at checkPosition (internal/fs/streams.js:57:11)
    at new ReadStream (internal/fs/streams.js:104:5)
```

**Comment by PeterRao** [comment]
文件大小多大呢

**Comment by jackieli123723** [comment]
@PeterRao  0kb 算是边际问题么？

**Comment by PeterRao** [comment]
> @PeterRao 0kb 算是边际问题么？

用的什么api进行上传的

**Comment by jackieli123723** [comment]
@PeterRao  nodejs 上传 

```js
const oss = require("ali-oss");
```

**Comment by PeterRao** [comment]
把上传文件发下吧，以及调用的代码。

**Comment by jackieli123723** [comment]
@PeterRao   运行node upload.js

## upload.js 
```js

const fs = require("fs");
const co = require("co");
const path = require("path");
const oss = require("ali-oss");
const ossPath = `xxxx`; //oss bucket path
const store = oss({
  region: `${process.env.REGION}`,
  accessKeyId: `${process.env.ACCESSKEYID}`,
  accessKeySecret: `${process.env.ACCESSKEYSECRET}`,
  bucket: `${process.env.BUCKET}`,
});

(() => {
  const root = path.resolve(__dirname, "./dist"); //在dist目录中例如有个文件 /dist/static/a.css 这个文件为0kb
  const files = [];
  function readDirSync(p) {
    const pa = fs.readdirSync(p);
    pa.forEach((e) => {
      const cur_path = `${p}/${e}`;
      const info = fs.statSync(cur_path);
      if (info.isDirectory()) {
        readDirSync(cur_path);
      } else {
        files.push(cur_path);
      }
    });
  }
  readDirSync(root);

  co(function*() {
    for (let index = 0; index < files.length; index += 1) {
      const e = files[index];
      const result = yield store.multipartUpload(
        ossPath + e.replace(root, ""),
        e,
        {
          progress: function*(p) {},
        }
      );

    }
  });
})();


```

**Comment by PeterRao** [comment]
不是0kb的有问题吗，我用0kb的文件，没复现出来。
