### ISSUE TITLE
上传图片报 'Client.requestError'

### ISSUE THREAD

**Issue by biyongzhi** [ali-sdk/ali-oss#792]
1.这是我的配置
const client = new OSS({
            region: res.data.region,
            accessKeyId: res.data.accessKeyId,
            accessKeySecret: res.data.accessKeySecret,
            bucket: res.data.bucket,
            timeout: 600000
          });
          let storeAs =
            'image/' +
            String(new Date().getFullYear()).slice(2, 4) +
            String(new Date().getMonth() + 1 + 100).slice(1, 3) +
            this.random_string() +
            '.' +
            options.file.name.split('.').pop();
          client
            .multipartUpload(storeAs, options.file)
            .then(res => {
              console.log(res);
            })
            .catch(err => {
              console.log(err);
            });
2.这是报错信息
RequestError: XHR error (req "error"), PUT http://jimu-edu.cn-beijing.aliyuncs.com/image/2005yiGefx6F2CMaEdtDDWNTDrk4AaXGdHsf.png -1 (connected: false, keepalive socket: false)
headers: {}
    at Client.requestError$ (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:535:19)
    at tryCatch (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:19953:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20187:22)
    at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20005:21)
    at tryCatch (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:19953:40)
    at invoke (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20043:20)
    at eval (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20086:11)
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20085:16)
    at AsyncIterator.enqueue [as _invoke] (webpack-internal:///./node_modules/ali-oss/dist/aliyun-oss-sdk.js:20108:13)

**Comment by PeterRao** [comment]
cn-beijing -> oss-cn-beijing, 详细region参考 https://help.aliyun.com/document_detail/31837.html

**Comment by biyongzhi** [comment]
> cn-beijing -> oss-cn-beijing, 详细region参考 https://help.aliyun.com/document_detail/31837.html

谢谢老哥，确实是这个问题。一开始我用的是后台返回的'cn-beijing ',结果应该是要写死的
