### ISSUE TITLE
nodejs 无法使用multipartUpload函数

### ISSUE THREAD

**Issue by Ryuurock** [ali-sdk/ali-oss#863]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
    at validateString (internal/validators.js:117:11)
    at Object.extname (path.js:1229:5)
    at Client.apply [as multipartUpload] (/Users/longdaxia/workspace/xigua/new-scratch/scratch-gui/node_modules/ali-oss/lib/managed-upload.js:40:52)

**Comment by Ryuurock** [comment]
nodejs里有File对象吗🙂️

**Comment by PeterRao** [comment]
node里传入 路径
