### ISSUE TITLE
Error [UnknowError]: Unknow error, status: 200

### ISSUE THREAD

**Issue by zhangzhige** [ali-sdk/ali-oss#881]
2020-10-29 10:45:46: Error [UnknowError]: Unknow error, status: 200
2020-10-29 10:45:46:     at Client.requestError (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\client.js:428:15)
2020-10-29 10:45:46:     at Client.request (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\client.js:264:22)
2020-10-29 10:45:46:     at runMicrotasks (<anonymous>)
2020-10-29 10:45:46:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-10-29 10:45:46:     at Client.get (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\common\object\get.js:42:14)
2020-10-29 10:45:46:     at D:\workspace\MovieGallery\GeneratorMovie\src\packages\nexrender-core\src\tasks\/download.js:52:13 {
2020-10-29 10:45:46:   status: 200,
2020-10-29 10:45:46:   requestId: '5F9A2C9F227FE63135312064',
2020-10-29 10:45:46:   host: ''
2020-10-29 10:45:46: }
2020-10-29 10:45:46: Error [UnknowError]: Unknow error, status: 200
2020-10-29 10:45:46:     at Client.requestError (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\client.js:428:15)
2020-10-29 10:45:46:     at Client.request (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\client.js:264:22)
2020-10-29 10:45:46:     at runMicrotasks (<anonymous>)
2020-10-29 10:45:46:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-10-29 10:45:46:     at Client.get (D:\workspace\MovieGallery\GeneratorMovie\node_modules\_ali-oss@6.8.0@ali-oss\lib\common\object\get.js:42:14)
2020-10-29 10:45:46:     at D:\workspace\MovieGallery\GeneratorMovie\src\packages\nexrender-core\src\tasks\/download.js:52:13 {
2020-10-29 10:45:46:   status: 200,
2020-10-29 10:45:46:   requestId: '5F9A2C9F227FE63135312064',
2020-10-29 10:45:46:   host: ''
2020-10-29 10:45:46: }

**Comment by PeterRao** [comment]
能稳定复现吗，可以加钉钉群 协助你看下

**Comment by zhangzhige** [comment]
> 我的服务会一直下载文件，大概率2-3天就能出现几个小时这个错误，怎么加群

**Comment by zhangzhige** [comment]
> 你
我的服务会一直下载文件，大概率2-3天就能出现几个小时这个错误，怎么加群

**Comment by huanggaoqing** [comment]
这个issues有解决办法吗
