### ISSUE TITLE
ImageClient getInfo 返回错误 NoSuchKey

### ISSUE THREAD

**Issue by patrick-xing** [ali-sdk/ali-oss#958]
* **Browser Version or Node Version**:
* node 14.17
* **ali-oss Version**:
* 6.15.2
* **Network Resoponse Header x-oss-request-id**:
{
  "name": "NoSuchKeyError",
  "status": 404,
  "code": "NoSuchKey",
  "requestId": "60C042DE617267353899342B",
  "hostId": "art-static.oss-cn-hangzhou.aliyuncs.com",
  "params": {
    "object": "exhibition/cover/B4B0NjJc2E.webp@infoexif",
    "bucket": "art-static",
    "method": "GET",
    "successStatuses": [
      200
    ]
  },
  "stacktrace": [
    "NoSuchKeyError: The specified key does not exist.",
    "    at Client.requestError (/app/node_modules/ali-oss/lib/client.js:367:11)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "    at async Client.request (/app/node_modules/ali-oss/lib/client.js:200:11)",
    "    at async Client.proto.request (/app/node_modules/ali-oss/lib/client.js:184:12)",
    "    at async ImageClient.getInfo (/app/node_modules/ali-oss/lib/image.js:70:18)",
  ]
}

使用put上传后，使用返回的result.name 获取imageinfo，为什么增加一个@infoexif，浏览器直接访问也会返回`NoSuchKeyError`

**Comment by xnng** [comment]
我也遇到了这个问题

**Comment by xiaodonghui** [comment]
我也遇到这个问题了，这么多年了一直没解决啊。。。
