### ISSUE TITLE
Unexpected token (2677:183) in node_modules/ali-oss/dist/aliyun-oss-sdk.js

### ISSUE THREAD

**Issue by duskmoon314** [ali-sdk/ali-oss#964]
* **Browser Version or Node Version**: 14.17.0
* **ali-oss Version**: 6.15.2
* **Mini Showcase Repository**: Not yet realized

I'm migrating a react-ts project from cra to vite, and I cannot build because this error. I can use ali-oss in the cra project with no problems.

I am now trying to build a mini showcase repo.

```
[commonjs] Unexpected token (2677:183) in /node_modules/ali-oss/dist/aliyun-oss-sdk.js
file: /node_modules/ali-oss/dist/aliyun-oss-sdk.js:2677:183 
2675:             params.successStatuses = [200];
2676:             params.xmlResponse = true;
2677:             _context.next = 6;
                                    ^
2678:             return this.request(params);
error during build:
SyntaxError: Unexpected token (2677:183) in /node_modules/ali-oss/dist/aliyun-oss-sdk.js
    at Parser.pp$4.raise (\node_modules\rollup\dist\shared\rollup.js:16781:13)
    at Parser.pp.unexpected (\node_modules\rollup\dist\shared\rollup.js:14289:8)
    at Parser.pp.semicolon (\node_modules\rollup\dist\shared\rollup.js:14266:64)
    at Parser.pp$1.parseExpressionStatement (\node_modules\rollup\dist\shared\rollup.js:14747:8)
    at Parser.pp$1.parseStatement (\node_modules\rollup\dist\shared\rollup.js:14482:24)
    at Parser.pp$1.parseBlock (\node_modules\rollup\dist\shared\rollup.js:14763:21)
    at Parser.pp$1.parseStatement (\node_modules\rollup\dist\shared\rollup.js:14447:34)
    at Parser.pp$1.parseBlock (\node_modules\rollup\dist\shared\rollup.js:14763:21)
    at Parser.pp$3.parseFunctionBody (\node_modules\rollup\dist\shared\rollup.js:16609:22)
    at Parser.pp$1.parseFunction (\node_modules\rollup\dist\shared\rollup.js:14885:8)
error Command failed with exit code 1.
```

**Comment by duskmoon314** [comment]
I cannot simply reproduce this problem. It seems like using the newest upload component of ant.design with oss has no problems. (This problem occurs in a repo using an older version of ant.design)

So I close this issue for now.
